### ISSUE TITLE
Bump python version to 3.9 -or- fix AttributeError: module 'importlib.resources' has no attribute 'files'

### ISSUE THREAD

**Issue by jeffrey-hicks** [messense/typst-py#12]
I am trying to use typst-py in Python 3.8 because I'm having to run on an older computer temporarily.  When I try using typst.compile(...) I get `AttributeError: module 'importlib.resources' has no attribute 'files'`, which nearest I can track down is because the files attribute appears to have come about in Python 3.9. [Importlib docs](https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy)

**Comment by jeffrey-hicks** [comment]
Thank you very much for helping.

**Comment by PPakalns** [comment]
Fix doesn't work.

In reality importlib.resources are defined in python 3.8, therefore importlib_resources are not imported.
