### ISSUE TITLE
Set Font as an option

### ISSUE THREAD

**Issue by drskoolie** [messense/typst-py#66]
In typst, you can set the font you want when you compile it via the command line. Can this functionality to be replicated for the Python one as well?

**Comment by messense** [comment]
Sorry I don't understand what did mean by set the font, there is already a `font_paths` option in https://github.com/messense/typst-py/blob/9fdeed6cbf21d352cd851859ca9ae58611da2a6e/python/typst/__init__.pyi#L11

I can't find any other options beside `--font-path` and `--ignore-system-fonts` in typst cli.
