### ISSUE TITLE
Support the `--pdf-standard` command line parameter

### ISSUE THREAD

**Issue by Marco-Kaulea** [messense/typst-py#67]
The `typst compile` command takes a parameter specifying the PDF standard to enforce conformance with. It would be useful to be able to do this through the Python module.
```
      --pdf-standard <PDF_STANDARD>
          One (or multiple comma-separated) PDF standards that Typst will
          enforce conformance with

          Possible values:
          - 1.7:  PDF 1.7
          - a-2b: PDF/A-2b
```

**Comment by messense** [comment]
Pull requests are welcome!

**Comment by Marco-Kaulea** [comment]
Haven't yet worked with Rust/Python integration, but I'm going to take a look.
