### ISSUE TITLE
Libertinus Serif font missing

### ISSUE THREAD

**Issue by ParaN3xus** [messense/typst-py#68]
Compile a document with default font(which is Libertinus Serif under typst 0.12.0) generates wrong document. The font fallback to some random sans font.
![image](https://github.com/user-attachments/assets/a7c3a3b3-db75-4748-a73b-688d6069c394)

**Comment by Coekjan** [comment]
It would be better to use typst-assets, instead of manually maintaining typst fonts in `python/typst/fonts`

**Comment by messense** [comment]
Thanks for the advice @Coekjan, I've switch to use `typst-kit` instead.
